name: publish to CHCR
on : 
  push:
    branches:
    - main

env:
  registry: ghcr.io
  Image_name: ${{ github.repository}}
jobs:
  gncr:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: logit to Docker
        uses: docker/login-action@v3
        with: 
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
            images: ${{ env.registry }}/${{ env.Image_name }}
      
      - name: Docker build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels : ${{ steps.meta.outputs.labels }}
        
      - name: Portainer webhook
        run : |
         echo "Deployed ${{ env.registry }}/${{ env.Image_name }}:${{ steps.meta.outputs.tags }}"
         
